"""Deutsche Stoppwörter für Cover-Schlagwortwolken (SSOT, ohne Extra-Paket)."""

from __future__ import annotations

# Kompakte DE-Liste für Cover-Wolken (häufige Funktionswörter + typische
# Buch-/Ratgeber-Füllwörter). Erweiterbar über den Dialog-Freitext.
GERMAN_STOPWORDS: frozenset[str] = frozenset(
    {
        "aber",
        "alle",
        "allem",
        "allen",
        "aller",
        "alles",
        "als",
        "also",
        "am",
        "an",
        "ander",
        "andere",
        "anderem",
        "anderen",
        "anderer",
        "anderes",
        "andern",
        "anders",
        "auch",
        "auf",
        "aus",
        "bei",
        "bin",
        "bis",
        "bist",
        "da",
        "dadurch",
        "daher",
        "darum",
        "das",
        "daß",
        "dass",
        "dein",
        "deine",
        "dem",
        "den",
        "der",
        "des",
        "dessen",
        "deshalb",
        "die",
        "dies",
        "diese",
        "diesem",
        "diesen",
        "dieser",
        "dieses",
        "doch",
        "dort",
        "du",
        "durch",
        "ein",
        "eine",
        "einem",
        "einen",
        "einer",
        "eines",
        "er",
        "es",
        "euer",
        "eure",
        "für",
        "fuer",
        "hatte",
        "hatten",
        "hattest",
        "hattet",
        "hier",
        "hinter",
        "ich",
        "ihr",
        "ihre",
        "im",
        "in",
        "ist",
        "ja",
        "jede",
        "jedem",
        "jeden",
        "jeder",
        "jedes",
        "jener",
        "jenes",
        "jetzt",
        "kann",
        "kannst",
        "können",
        "koennen",
        "könnt",
        "koennt",
        "machen",
        "mein",
        "meine",
        "mit",
        "muß",
        "muss",
        "mußt",
        "musst",
        "müssen",
        "muessen",
        "müßt",
        "muesst",
        "nach",
        "nachdem",
        "nein",
        "nicht",
        "nun",
        "oder",
        "seid",
        "sein",
        "seine",
        "sich",
        "sie",
        "sind",
        "soll",
        "sollen",
        "sollst",
        "sollt",
        "sonst",
        "soweit",
        "sowie",
        "und",
        "unser",
        "unsere",
        "unter",
        "vom",
        "von",
        "vor",
        "wann",
        "warum",
        "was",
        "weiter",
        "weitere",
        "wenn",
        "wer",
        "werde",
        "werden",
        "werdet",
        "weshalb",
        "wie",
        "wieder",
        "wieso",
        "wir",
        "wird",
        "wirst",
        "wo",
        "woher",
        "wohin",
        "zu",
        "zum",
        "zur",
        "über",
        "ueber",
        # typische Ratgeber-/Markdown-Reste
        "bzw",
        "ca",
        "etc",
        "inkl",
        "vgl",
        "z.b",
        "zb",
        "https",
        "http",
        "www",
        "md",
        "title",
        "author",
    }
)


def merge_stopwords(*extra: str | None) -> list[str]:
    """Combine German defaults with optional extra tokens (lowercased)."""
    words = set(GERMAN_STOPWORDS)
    for item in extra:
        if not item:
            continue
        for token in str(item).replace(",", " ").split():
            cleaned = token.strip().lower()
            if cleaned:
                words.add(cleaned)
    return sorted(words)
